require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRailsVersion: 5.1
  Exclude:
    - 'vendor/**/*'
  DisplayCopNames: true
  DisplayStyleGuide: true

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test

Metrics/BlockLength:
  Exclude:
    - '**/Guardfile'
    - '**/*.rake'
    - 'config/environments/*'
    - 'config/routes.rb'
    - 'test/**/*'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Rails/HttpPositionalArguments:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# Enable cops that are disabled by default, but are useful nonetheless
# See https://github.com/bbatsov/rubocop/blob/master/config/disabled.yml

Rails:
  Enabled: true